apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: keycloak
spec:
  project: default
  source:
    repoURL: https://github.com/hiteshsp/kubeflow-keycloak.git
    targetRevision: HEAD
    path: environment/dev/keycloak
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    name: in-cluster
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground
    - PruneLast=true 
    managedNamespaceMetadata: 
      labels: 
        application: keycloak
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 